spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: order_service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
          filters:
            - name: OrderServiceFilter
